#Lyrics.py
#Designed to just echo out the lyrics to the console while in sync with the music.
#Lets start!
import time
import os
import pygame

file = 'stillalivehq.mp3'
pygame.init()
pygame.mixer.init()
pygame.mixer.music.load(file)

def lyric( str ):
  	"Lyrics printed out through this command should be orange"
	#time.sleep(1)
	print "\033[38;5;208m" + str + "\033[0;00m"
	return
os.system("clear")
pygame.mixer.music.play()
lyric("This was a triumph.")
time.sleep(4)
lyric("I'm making a note here:")
time.sleep(2)
lyric("HUGE SUCCESS.")
time.sleep(3)
lyric("It's hard to overstate ")
time.sleep(2)
lyric("my satisfaction.")
time.sleep(5)
lyric("Aperture Science ")
time.sleep(4)
lyric("We do what we must")
time.sleep(2.2)
lyric("because we can.")
time.sleep(3)
lyric("For the good of all of us.")
time.sleep(3)
lyric("Except the ones who are dead.")
time.sleep(2)
lyric("But there's no sense crying")
time.sleep(2.5)
lyric("over every mistake.")
time.sleep(2)
lyric("You just keep on trying ")
time.sleep(2)
lyric("till you run out of cake.")
time.sleep(2)
lyric("And the Science gets done.")
time.sleep(2)
lyric("And you make a neat gun.")
time.sleep(2)
lyric("For the people who are")
time.sleep(2)
lyric("still alive.")
time.sleep(1)
lyric("")
lyric("")
lyric("")
#page2
os.system("clear")
time.sleep(7)
lyric("I'm not even angry.")
time.sleep(4)
lyric("I'm being so sincere right now.")
time.sleep(5)
lyric("Even though you broke my heart.")
time.sleep(3)
lyric("And killed me.")
time.sleep(3.5)
lyric("And tore me to pieces.")
time.sleep(3.5)
lyric("And threw every piece into a fire.")
time.sleep(5)
lyric("As they burned it hurt because")
time.sleep(3)
lyric("I was so happy for you!")
time.sleep(2.5)
lyric("Now these points of data")
time.sleep(2)
lyric("make a beautiful line")
time.sleep(2)
lyric("And we're out of beta. ")
time.sleep(2) #30
lyric("We're releasing on time.")
time.sleep(2)
lyric("So I'm GLaD. I got burned.")
time.sleep(2)
lyric("Think of all the things we learned")
time.sleep(1.7)
lyric("For the people who are")
time.sleep(2)
lyric("still alive.")
time.sleep(2)
#pg3
lyric("")
lyric("")
lyric("")
os.system("clear")
time.sleep(6)
lyric("Go ahead and leave me.")
time.sleep(3.8)
lyric("I think I prefer to stay inside.")
time.sleep(5)
lyric("Maybe you'll find someone else")
time.sleep(4)
lyric("to help you.")
time.sleep(3.5)
lyric("Maybe Black Mesa,")
time.sleep(3)
lyric("THAT WAS A JOKE. FAT CHANCE.")
time.sleep(4.6)
lyric("Anyway, this cake is great.")
time.sleep(3)
lyric("It's so delicious and moist.")
time.sleep(2.5)
lyric("Look at me still talking ")
time.sleep(2.5)
lyric("When there's Science to do.")
time.sleep(2.5)
lyric("When I look out there,")
time.sleep(2)
lyric("It makes me Glad I'm not you.")
time.sleep(2)
lyric("I've experiments to run.")
time.sleep(2)
lyric("There is research to be done.")
time.sleep(2)
lyric("On the people who are")
time.sleep(2)
lyric("still alive.")
time.sleep(2)
os.system("clear")
time.sleep(1)
#pg4
lyric("PS: And believe me I am")
time.sleep(1.5)
lyric("still alive.")
time.sleep(1.5)
lyric("PPs: I'm doing science and I'm")
time.sleep(1.8)
lyric("still alive.")
time.sleep(1.8)
lyric("PPPS: I feel FANTASTIC and I'm")
time.sleep(1.8)
lyric("still alive.")
time.sleep(1.8)
lyric("While you're dying I'll be")
time.sleep(1.8)
lyric("still alive.")
time.sleep(1.8)
lyric("FINAL THOUGHT PS:")
time.sleep(1.8)
lyric("And when you're dead I will be")
time.sleep(1.8)
lyric("still alive.")
time.sleep(2)
lyric("STILL ALIVE")
time.sleep(1)
os.system("clear")

while pygame.mixer.music.get_busy():
  pygame.time.Clock().tick(10)

